version: '3.9'
services:
  nginx: 
    image: nginx:stable-alpine
    depends_on:
      - php
      - mysql
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html:delegated

  mysql:
    image: mysql/mysql-server:8.0.23
    env_file: docker/docker.env
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '9081:80'
    environment:
      UPLOAD_LIMIT: 1024M
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: secret

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: ['composer'] # Install without other php modules required

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html:delegated
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "9000:9000"
  wp:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./src:/var/www/html:delegated
    entrypoint: ['wp', '--allow-root']
